// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://xcficycixgiooylawchu.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZmljeWNpeGdpb295bGF3Y2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzMzQ3ODIsImV4cCI6MjA0NzkxMDc4Mn0.VsqT2i_SH1pYvl841W5NBh9_6tUE6nLgI3wzq3d0NQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);